name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZWU2Nzg0N2EtYzhmZi00MjNjLWEzZGUtZjczMTZjNDQzODRmIiwidGVuYW50X2lkIjoiNWQ0Y2E3ODVmYTYyZWEwNmU0ODdlOWZlNWVkNjU3OTFhZjBmNzZkZTNhYzZlMmE5OGZhY2NiYmUxODM4Njc4NyIsImludGVybmFsX3NlY3JldCI6IjEwZDVjODVlLTFkNjItNDk4MS04YzczLWIwZDFkMzdlZmRhYSJ9.6jJ3mliuP6Ch3Z-OdiPYQlxLTgtDjCXnr2dMb9CP1Bc"
JWT_SECRET="abc123"